/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Cadastros;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import static javax.swing.JFileChooser.DIRECTORIES_ONLY;
import static javax.swing.JFileChooser.FILES_ONLY;

/**
 *
 * @author Hilton
 */
public class SelecionaCapa extends javax.swing.JDialog {

    /**
     * Creates new form SelecionaCapa
     */
    public File file;
    private String padrao = "";

    public SelecionaCapa(java.awt.Frame parent, boolean modal, String nome, int tipo,String titulo) throws IOException {
        super(parent, modal);
        initComponents();
        if (tipo == 1) {
            jFCarquivo.setFileSelectionMode(DIRECTORIES_ONLY);
        } else {
            jFCarquivo.setFileSelectionMode(FILES_ONLY);
        }

        padrao = new File(".").getCanonicalPath() + "\\capas";
        System.out.println(nome);
        jFCarquivo.setCurrentDirectory(new File(padrao));
//        JOptionPane.showMessageDialog(null, padrao);

        setTitle(titulo);
        jFCarquivo.setSelectedFile(new java.io.File(nome));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/biblioteca_24.png")));
    }
    
    public SelecionaCapa(java.awt.Frame parent, boolean modal, String nome, int tipo,String titulo, int aux) throws IOException {
        super(parent, modal);
        initComponents();
        if (tipo == 1) {
            jFCarquivo.setFileSelectionMode(DIRECTORIES_ONLY);
        } else {
            jFCarquivo.setFileSelectionMode(FILES_ONLY);
        }

        padrao = new File(".").getCanonicalPath() + "\\capas";
        System.out.println(nome);
        jFCarquivo.setCurrentDirectory(new File(nome));
//        JOptionPane.showMessageDialog(null, padrao);

        setTitle(titulo);
        jFCarquivo.setSelectedFile(new java.io.File(nome));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/biblioteca_24.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFCarquivo = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFCarquivo.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        jFCarquivo.setApproveButtonText("Selecionar");
        jFCarquivo.setApproveButtonToolTipText("Selecionar");
        jFCarquivo.setCurrentDirectory(new File(padrao));
        jFCarquivo.setDialogTitle("Selecionar");
        jFCarquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFCarquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFCarquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFCarquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(662, 436));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFCarquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFCarquivoActionPerformed
        this.file = jFCarquivo.getSelectedFile();
        System.out.println(file);
        this.dispose();
    }//GEN-LAST:event_jFCarquivoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SelecionaCapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SelecionaCapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SelecionaCapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SelecionaCapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SelecionaCapa dialog = new SelecionaCapa(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFCarquivo;
    // End of variables declaration//GEN-END:variables
}
