/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Gerais;

import Frames.Cadastros.CadastroArquivos;
import Frames.Cadastros.CadastroAutores;
import Frames.Cadastros.CadastroCategorias;
import Frames.Cadastros.CadastroEditoras;
import Frames.Cadastros.CadastroLivros;
import Frames.Cadastros.CadastroUsuarios;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.TelaTemas;

/**
 *
 * @author hilton
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial(int i_usuario, String nomeUsuario, String nivel) {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/biblioteca_32.png")));
        jLstatus.setText(new util.Persistencia().conectar().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jBcategorias = new javax.swing.JButton();
        jBeditoras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBlivros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBautores = new javax.swing.JButton();
        jBarquivos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        desk = new javax.swing.JDesktopPane();
        jLstatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMbackup = new javax.swing.JMenuItem();
        jMconfig = new javax.swing.JMenuItem();
        jMItemas = new javax.swing.JMenuItem();
        jMsair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIlivros = new javax.swing.JMenuItem();
        jMIautores = new javax.swing.JMenuItem();
        jMIcategorias = new javax.swing.JMenuItem();
        jMIeditoras = new javax.swing.JMenuItem();
        jMIarquivos = new javax.swing.JMenuItem();
        jMIusuarios = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIBLIOTECA");
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBcategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categoria_64.png"))); // NOI18N
        jBcategorias.setMargin(new java.awt.Insets(2, 6, 2, 6));
        jBcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcategoriasActionPerformed(evt);
            }
        });

        jBeditoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editora_64.png"))); // NOI18N
        jBeditoras.setMargin(new java.awt.Insets(2, 6, 2, 6));
        jBeditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditorasActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LIVROS");

        jBlivros.setForeground(new java.awt.Color(0, 102, 204));
        jBlivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biblioteca_64.png"))); // NOI18N
        jBlivros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBlivros.setMargin(new java.awt.Insets(2, 6, 2, 6));
        jBlivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlivrosActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CATEGORIAS");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EDITORAS");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("AUTORES");

        jBautores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/autor_64.png"))); // NOI18N
        jBautores.setToolTipText("");
        jBautores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBautores.setMargin(new java.awt.Insets(2, 6, 2, 6));
        jBautores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBautoresActionPerformed(evt);
            }
        });

        jBarquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arquivo_64.png"))); // NOI18N
        jBarquivos.setMargin(new java.awt.Insets(2, 6, 2, 6));
        jBarquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarquivosActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ARQUIVOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBlivros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBcategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(jBeditoras, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBautores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBarquivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBautores, jBcategorias, jBeditoras, jBlivros, jLabel2, jLabel3, jLabel4, jLabel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBlivros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBautores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBcategorias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBeditoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBarquivos)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        desk.setBackground(new java.awt.Color(240, 240, 240));
        desk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        desk.setPreferredSize(new java.awt.Dimension(735, 610));

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(desk);

        jLstatus.setText(".");
        jLstatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setText("Arquivos");

        jMbackup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backup_32.png"))); // NOI18N
        jMbackup.setText("Backup");
        jMbackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMbackupActionPerformed(evt);
            }
        });
        jMenu1.add(jMbackup);

        jMconfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/config_32.png"))); // NOI18N
        jMconfig.setText("Configurações");
        jMconfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMconfigActionPerformed(evt);
            }
        });
        jMenu1.add(jMconfig);

        jMItemas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tema_32.png"))); // NOI18N
        jMItemas.setText("Temas");
        jMItemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMItemasActionPerformed(evt);
            }
        });
        jMenu1.add(jMItemas);

        jMsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair_32.png"))); // NOI18N
        jMsair.setText("Sair");
        jMsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsairActionPerformed(evt);
            }
        });
        jMenu1.add(jMsair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastros");

        jMIlivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biblioteca_24.png"))); // NOI18N
        jMIlivros.setText("Livros");
        jMIlivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIlivrosActionPerformed(evt);
            }
        });
        jMenu2.add(jMIlivros);

        jMIautores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/autor_24.png"))); // NOI18N
        jMIautores.setText("Autores");
        jMIautores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIautoresActionPerformed(evt);
            }
        });
        jMenu2.add(jMIautores);

        jMIcategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/categoria_24.png"))); // NOI18N
        jMIcategorias.setText("Categorias");
        jMIcategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIcategoriasActionPerformed(evt);
            }
        });
        jMenu2.add(jMIcategorias);

        jMIeditoras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editora_24.png"))); // NOI18N
        jMIeditoras.setText("Editoras");
        jMIeditoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIeditorasActionPerformed(evt);
            }
        });
        jMenu2.add(jMIeditoras);

        jMIarquivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/arquivo_24.png"))); // NOI18N
        jMIarquivos.setText("Arquivos");
        jMIarquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIarquivosActionPerformed(evt);
            }
        });
        jMenu2.add(jMIarquivos);

        jMIusuarios.setText("Usuarios");
        jMIusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIusuariosActionPerformed(evt);
            }
        });
        jMenu2.add(jMIusuarios);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jLstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLstatus))
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMIautoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIautoresActionPerformed
        exibeFormularioInterno(new CadastroAutores(), "autor");
    }//GEN-LAST:event_jMIautoresActionPerformed

    private void jMsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMsairActionPerformed

    private void jBcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcategoriasActionPerformed
        exibeFormularioInterno(new CadastroCategorias(), "categoria");
    }//GEN-LAST:event_jBcategoriasActionPerformed

    private void jMIcategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIcategoriasActionPerformed
        exibeFormularioInterno(new CadastroCategorias(), "categoria");
    }//GEN-LAST:event_jMIcategoriasActionPerformed

    private void jBautoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBautoresActionPerformed
        exibeFormularioInterno(new CadastroAutores(), "autor");
    }//GEN-LAST:event_jBautoresActionPerformed

    private void jBeditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditorasActionPerformed
        exibeFormularioInterno(new CadastroEditoras(), "editora");
    }//GEN-LAST:event_jBeditorasActionPerformed

    private void jMIeditorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIeditorasActionPerformed
        exibeFormularioInterno(new CadastroEditoras(), "editora");
    }//GEN-LAST:event_jMIeditorasActionPerformed

    private void jMIusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIusuariosActionPerformed
        exibeFormularioInterno(new CadastroUsuarios(), "usuario");
    }//GEN-LAST:event_jMIusuariosActionPerformed

    private void jBlivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlivrosActionPerformed
        exibeFormularioInterno(new CadastroLivros(), "acervo");
    }//GEN-LAST:event_jBlivrosActionPerformed

    private void jMIlivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIlivrosActionPerformed
        exibeFormularioInterno(new CadastroLivros(), "acervo");
    }//GEN-LAST:event_jMIlivrosActionPerformed

    private void jMItemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemasActionPerformed
        try {
            TelaTemas t = new TelaTemas(new Frames.Gerais.TelaInicial(1, "admin", "admin"), rootPaneCheckingEnabled);
            t.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMItemasActionPerformed

    private void jMconfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMconfigActionPerformed
        try {
            ConfiguracoesGerais configuracoesGerais = new ConfiguracoesGerais(new Frames.Gerais.TelaInicial(1, "admin", "admin"), rootPaneCheckingEnabled);
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMconfigActionPerformed

    private void jMbackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMbackupActionPerformed
        try {
            BackupH2 b = new BackupH2(new Frames.Gerais.TelaInicial(1, "admin", "admin"), rootPaneCheckingEnabled);
            b.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMbackupActionPerformed

    private void jMIarquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIarquivosActionPerformed
        exibeFormularioInterno(new CadastroArquivos(), "arquivo");
    }//GEN-LAST:event_jMIarquivosActionPerformed

    private void jBarquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarquivosActionPerformed
        exibeFormularioInterno(new CadastroArquivos(), "arquivo");
    }//GEN-LAST:event_jBarquivosActionPerformed

    public void exibeForm1(javax.swing.JInternalFrame frame, String tipo) {
        //<editor-fold defaultstate="collapsed" desc="Controle dos Frames">
        /* Método controlador dos JInternalFrames*/
        javax.swing.JInternalFrame[] iframe = desk.getAllFrames();
        util.Centralizar c;
        if (iframe.length <= 0) {
            desk.add(frame);
            c = new util.Centralizar(frame);
            frame.setVisible(true);
        } else {
            switch (tipo) {
                case "autor":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("autor")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "categoria":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("categoria")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "editora":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("editora")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "acervo":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("acervo")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "usuario":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("usuario")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "arquivo":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("arquivo")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "anexo":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("anexo")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "controledeponto":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("controledeponto")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "configponto":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("configponto")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "cadastraperiodo":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("cadastraperiodo")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
                case "gerenciarregistrodeponto":
                    for (int i = 0; i < iframe.length; i++) {
                        if (iframe[i].getName().equals("gerenciarregistrodeponto")) {
                            i = iframe.length + 1;
                            return;
                        }
                    }//fim do for  
                    desk.add(frame);
                    c = new util.Centralizar(frame);
                    frame.setVisible(true);
                    break;
            }//fim do switch
        }//fim do else 
        //</editor-fold>
    }//fim do metodo

    public void exibeFormularioInterno(javax.swing.JInternalFrame frame, String tipo) {
        //<editor-fold defaultstate="collapsed" desc="Controle dos Frames">
        /* Método controlador dos JInternalFrames*/
        javax.swing.JInternalFrame[] iframe = desk.getAllFrames();
        util.Centralizar c;
        if (iframe.length <= 0) {
            desk.add(frame);
            c = new util.Centralizar(frame);
            frame.setVisible(true);
        } else {
            for (int i = 0; i < iframe.length; i++) {
                if (iframe[i].getName().equals(tipo)) {
                    i = iframe.length + 1;
                    return;
                }
            }//fim do for  
            desk.add(frame);
            c = new util.Centralizar(frame);
            frame.setVisible(true);
        }//fim do else 
        //</editor-fold>
    }//fim do metodo

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial(0, "admin", "0").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desk;
    private javax.swing.JButton jBarquivos;
    private javax.swing.JButton jBautores;
    private javax.swing.JButton jBcategorias;
    private javax.swing.JButton jBeditoras;
    private javax.swing.JButton jBlivros;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLstatus;
    private javax.swing.JMenuItem jMIarquivos;
    private javax.swing.JMenuItem jMIautores;
    private javax.swing.JMenuItem jMIcategorias;
    private javax.swing.JMenuItem jMIeditoras;
    private javax.swing.JMenuItem jMIlivros;
    private javax.swing.JMenuItem jMItemas;
    private javax.swing.JMenuItem jMIusuarios;
    private javax.swing.JMenuItem jMbackup;
    private javax.swing.JMenuItem jMconfig;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMsair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
